CREATE TABLE ARTICLES (
	id INTEGER NOT NULL AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	text VARCHAR(64999) NOT NULL,
	short VARCHAR(255) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE TABLE TAGS (
	articleID INTEGER NOT NULL,
	tag varchar(10) NOT NULL,
	PRIMARY KEY (articleID)
);
CREATE TABLE COMMENTS (
	articleID INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	text VARCHAR(64999) NOT NULL,
	PRIMARY KEY (articleID)
);

